insert into public.isle (name) values ('North Island'), ('South Island');

insert into public.region (name, isle) 
	values ('Northland', 'North Island'),
			('Auckland', 'North Island'),
			('Waikato', 'North Island'),
			('Bay of Plenty', 'North Island'),
			/*('Gisborne', 'North Island'),*/
			('Hawkes Bay', 'North Island'),
			('Taranaki', 'North Island'),
			('Manawatu-Wanganui', 'North Island'),
			('Wellington', 'North Island'),
			('Tasman', 'South Island'),
			('Nelson', 'South Island'),
			('Marlborough', 'South Island'),
			('West Coast', 'South Island'),
			('Canterbury', 'South Island'),
			('Otago', 'South Island'),
			('Southland', 'South Island');
			
					
insert into public.city (name, isle, region)
	values 
/*Noth Island*/
			/*Northland*/
			('Ruakaka', 'North Island', 'Northland'),
			('Kerikeri', 'North Island', 'Northland'),
			('Whangarei', 'North Island', 'Northland'),
			/*Auckland*/
			('Auckland', 'North Island', 'Auckland'),
			('Clevedon', 'North Island', 'Auckland'),
			('Helensville', 'North Island', 'Auckland'),
			('Manukau', 'North Island', 'Auckland'),
			('Huapai', 'North Island', 'Auckland'),	
			('Pukekohe', 'North Island', 'Auckland'),
			('Snells Beach', 'North Island', 'Auckland'),
			/*Waikato*/
			('Cambridge', 'North Island', 'Waikato'),	
			('Te Awamutu', 'North Island', 'Waikato'),
			('Hamilton', 'North Island', 'Waikato'),
			('Huntly', 'North Island', 'Waikato'),
			('Matamata', 'North Island', 'Waikato'),
			('Morrinsville', 'North Island', 'Waikato'),
			('Putaruru', 'North Island', 'Waikato'),
			('Thames', 'North Island', 'Waikato'),
			('Tairua', 'North Island', 'Waikato'),
			('Taupo', 'North Island', 'Waikato'),
			('Tokoroa', 'North Island', 'Waikato'),
			('Waihi', 'North Island', 'Waikato'),
			('Whangamata', 'North Island', 'Waikato'),
			('Whitianga', 'North Island', 'Waikato'),
			('Raglan', 'North Island', 'Waikato'),
			/*Bay of Plenty*/
			('Tauranga', 'North Island', 'Bay of Plenty'),
			('Rotorua', 'North Island', 'Bay of Plenty'),
			('Katikati', 'North Island', 'Bay of Plenty'),
			('Te Puke', 'North Island', 'Bay of Plenty'),
			('Whakatane', 'North Island', 'Bay of Plenty'),
			/*Gisborne*/
			/*Hawkes Bay*/
			('Napier', 'North Island', 'Hawkes Bay'),
			('Hastings', 'North Island', 'Hawkes Bay'),
			('Waipukurau', 'North Island', 'Hawkes Bay'),
			('Waipawa', 'North Island', 'Hawkes Bay'),
			/*Taranaki*/
			('New Plymouth', 'North Island', 'Taranaki'),
			('Inglewood', 'North Island', 'Taranaki'),
			('Stratford', 'North Island', 'Taranaki'),
			('Hawera', 'North Island', 'Taranaki'),
			('Waitara', 'North Island', 'Taranaki'),
			('Bell Block', 'North Island', 'Taranaki'),
			/*Manawatu-Wanganui*/
			('Dannevirke', 'North Island', 'Manawatu-Wanganui'),
			('Palmerston North', 'North Island', 'Manawatu-Wanganui'),
			('Feilding', 'North Island', 'Manawatu-Wanganui'),
			('Whanganui', 'North Island', 'Manawatu-Wanganui'),
			('Pahiatua', 'North Island', 'Manawatu-Wanganui'),
			('Taumarunui', 'North Island', 'Manawatu-Wanganui'),
			('Woodville', 'North Island', 'Manawatu-Wanganui'),
			/*Wellington*/
			('Masterton', 'North Island', 'Wellington'),
			('Otaki', 'North Island', 'Wellington'),
			('Lower Hutt', 'North Island', 'Wellington'),			
			('Porirua', 'North Island', 'Wellington'),
			('Wellington City', 'North Island', 'Wellington'),
			('Featherston', 'North Island', 'Wellington'),
			('Pauanui', 'North Island', 'Wellington'),	
/*South Island*/
			/*Marlborough*/
			('Picton', 'South Island', 'Marlborough'),
			('Blenheim', 'South Island', 'Marlborough'),
			('Renwick', 'South Island', 'Marlborough'),
			/*Nelson*/
			('Nelson', 'South Island', 'Nelson'),
			/*Tasman*/
			('Richmond', 'South Island', 'Tasman'),
			('Takaka', 'South Island', 'Tasman'),
			('Motueka', 'South Island', 'Tasman'),
			/*Canterbury*/
			('Christchurch', 'South Island', 'Canterbury'),
			('Geraldine', 'South Island', 'Canterbury'),
			('Leeston', 'South Island', 'Canterbury'),
			('Oxford', 'South Island', 'Canterbury'),
			('Prebbleton', 'South Island', 'Canterbury'),
			('Amberley', 'South Island', 'Canterbury'),
			('Hanmer Springs', 'South Island', 'Canterbury'),
			('Kaiapoi', 'South Island', 'Canterbury'),
			('Methven', 'South Island', 'Canterbury'),
			('Twizel', 'South Island', 'Canterbury'),
			('Lyttleton', 'South Island', 'Canterbury'),
			('Ashburton', 'South Island', 'Canterbury'),
			/*West Coast*/
			('Westport', 'South Island', 'West Coast'),
			('Greymouth', 'South Island', 'West Coast'),
			('Hokitika', 'South Island', 'West Coast'),
			('Reefton', 'South Island', 'West Coast'),
			/*Otago*/
			('Cromwell', 'South Island', 'Otago'),
			('Dunedin', 'South Island', 'Otago'),
			('Queenstown', 'South Island', 'Otago'),
			('Alexandra', 'South Island', 'Otago'),
			('Balclutha', 'South Island', 'Otago'),
			('Oamaru', 'South Island', 'Otago'),
			('Wanaka', 'South Island', 'Otago'),
			('Milton', 'South Island', 'Otago'),
			('Roxburgh', 'South Island', 'Otago'),
			/*Southland*/
			('Te Anau', 'South Island', 'Southland'),
			('Invercargill', 'South Island', 'Southland'),
			('Wallacetown', 'South Island', 'Southland'),
			('Otautau', 'South Island', 'Southland'),
			('Riverton', 'South Island', 'Southland');
			
insert into public.market (name, generic_url, max_page_add)
	values  ('Big Barrel', false, '&pagesize=48'),
			('FreshChoice', false, null),
			('Super Liquor', false, '&pagesize=24'),
			('SuperValue', false, null);
			
insert into public.market_info (market,
								 search_container_type,
							 	 search_container_class,
								 product_container_type,
								 product_container_class,
								 product_link_container_type,
								 product_link_container_class,
								 product_link_element_type,
								 product_image_container_type,
								 product_image_container_class,
								 product_image_element_type,
								 product_image_element_class,
								 product_image_element_param,
								 product_detail_container_type,
								 product_detail_container_class,
								 product_name_container_type,
								 product_name_container_class,
								 product_name_element_type,
								 product_price_container_type,
								 product_price_container_class,
								 product_price_element_type,
								 product_price_element_class)
	values	
/*name*/				   		   ('Big Barrel', 
/*search_container_type*/			'div',
/*search_container_class*/			'search-results',
/*product_container_type*/			'div',
/*product_container_class*/			'item-box',
/*product_link_container_typer*/	'div',
/*product_link_container_class*/	'picture',
/*product_link_element_type*/		'a',
/*product_image_container_type*/	'div',
/*product_image_container_class*/	'picture',
/*product_image_element_type*/		'img',
/*product_image_element_class*/		null,
/*product_image_element_param*/		'src',
/*product_detail_container_type*/	'div',
/*product_detail_container_class*/	'details',
/*product_name_container_type*/		'h2',
/*product_name_container_class*/	'product-title',
/*product_name_element_type*/		'a',
/*product_price_container_type*/	'div',
/*product_price_container_class*/	'prices',
/*product_price_element_type*/		'span',
/*product_price_element_class*/		'price actual-price'),

/*name*/				   		   ('FreshChoice', 
/*search_container_type*/			'div',
/*search_container_class*/			'shopping-list search_results',
/*product_container_type*/			'div',
/*product_container_class*/			'TalkerGrid__Item',
/*product_link_container_type*/		'div',
/*product_link_container_class*/	'talker__section talker__section--image',
/*product_link_element_type*/		'a',
/*product_image_container_type*/	'div',
/*product_image_container_class*/	'talker__section talker__section--image',
/*product_image_element_type*/		'img',
/*product_image_element_class*/		null,
/*product_image_element_param*/		'src',
/*product_detail_container_type*/	'div',
/*product_detail_container_class*/	'talker__details',
/*product_name_container_type*/		'div',
/*product_name_container_class*/	'talker__name talker__section',
/*product_name_element_type*/		'span',
/*product_price_container_type*/	'div',
/*product_price_container_class*/	'talker__prices__sell',
/*product_price_element_type*/		'strong',
/*product_price_element_class*/		null),

/*name*/				   		   ('Super Liquor', 
/*search_container_type*/			'div',
/*search_container_class*/			'product-grid',
/*product_container_type*/			'div',
/*product_container_class*/			'item-box',
/*product_link_container_typer*/	'div',
/*product_link_container_class*/	'product-title',
/*product_link_element_type*/		'a',
/*product_image_container_type*/	'div',
/*product_image_container_class*/	'picture',
/*product_image_element_type*/		'img',
/*product_image_element_class*/		'img-fluid',
/*product_image_element_param*/		'data-src',
/*product_detail_container_type*/	'div',
/*product_detail_container_class*/	'details',
/*product_name_container_type*/		'div',
/*product_name_container_class*/	'product-title text-uppercase',
/*product_name_element_type*/		'a',
/*product_price_container_type*/	'div',
/*product_price_container_class*/	'prices',
/*product_price_element_type*/		'span',
/*product_price_element_class*/		'price actual-price'),

/*name*/				   		   ('SuperValue', 
/*search_container_type*/			'div',
/*search_container_class*/			'shopping-list search_results',
/*product_container_type*/			'div',
/*product_container_class*/			'TalkerGrid__Item',
/*product_link_container_typer*/	'div',
/*product_link_container_class*/	'talker__section talker__section--image',
/*product_link_element_type*/		'a',
/*product_image_container_type*/	'div',
/*product_image_container_class*/	'talker__section talker__section--image',
/*product_image_element_type*/		'img',
/*product_image_element_class*/		null,
/*product_image_element_param*/		'src',
/*product_detail_container_type*/	'div',
/*product_detail_container_class*/	'talker__details',
/*product_name_container_type*/		'div',
/*product_name_container_class*/	'talker__name talker__section',
/*product_name_element_type*/		'span',
/*product_price_container_type*/	'div',
/*product_price_container_class*/	'talker__prices talker__section',
/*product_price_element_type*/		'strong',
/*product_price_element_class*/		null);


insert into public.store (name, market, isle, region, city, store_url, store_search_url)
	values
/*Noth Island*/
			/*Northland*/
			('FreshChoice Ruakaka', 'FreshChoice', 'North Island', 'Northland', 'Ruakaka', 'https://ruakaka.store.freshchoice.co.nz','https://ruakaka.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('Super Liquor Kerikeri', 'Super Liquor', 'North Island', 'Northland', 'Kerikeri', 'https://kerikeri.superliquor.co.nz', 'https://kerikeri.superliquor.co.nz/search?q='),
			('Super Liquor Okara', 'Super Liquor', 'North Island', 'Northland', 'Whangarei', 'https://okara.superliquor.co.nz', 'https://okara.superliquor.co.nz/search?q='),
			('Super Liquor Onerahi', 'Super Liquor', 'North Island', 'Northland', 'Whangarei', 'https://onerahi.superliquor.co.nz', 'https://onerahi.superliquor.co.nz/search?q='),	
			/*Auckland*/
			('FreshChoice Epson', 'FreshChoice', 'North Island', 'Auckland', 'Auckland', 'https://epsom.store.freshchoice.co.nz','https://epsom.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Glen Eden', 'FreshChoice', 'North Island', 'Auckland', 'Auckland', 'https://gleneden.store.freshchoice.co.nz', 'https://gleneden.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Half Moon Bay', 'FreshChoice', 'North Island', 'Auckland', 'Auckland', 'https://halfmoonbay.store.freshchoice.co.nz', 'https://halfmoonbay.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Mangere Bridge', 'FreshChoice', 'North Island', 'Auckland', 'Auckland', 'https://mangerebridge.store.freshchoice.co.nz', 'https://mangerebridge.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Otahuhu', 'FreshChoice', 'North Island', 'Auckland', 'Auckland', 'https://otahuhu.store.freshchoice.co.nz', 'https://otahuhu.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Ranui', 'FreshChoice', 'North Island', 'Auckland', 'Auckland', 'https://ranui.store.freshchoice.co.nz', 'https://ranui.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Waimauku', 'FreshChoice', 'North Island', 'Auckland', 'Auckland', 'https://waimauku.store.freshchoice.co.nz', 'https://waimauku.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('Super Liquor Beachlands', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://beachlands.superliquor.co.nz', 'https://beachlands.superliquor.co.nz/search?q='),
			('Super Liquor Clevedon', 'Super Liquor', 'North Island', 'Auckland', 'Clevedon', 'https://clevedon.superliquor.co.nz', 'https://clevedon.superliquor.co.nz/search?q='),
			('Super Liquor Flat Bush', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://flatbush.superliquor.co.nz', 'https://flatbush.superliquor.co.nz/search?q='),
			('Super Liquor Glen Innes', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://gleninnes.superliquor.co.nz', 'https://gleninnes.superliquor.co.nz/search?q='),
			('Super Liquor Greenlane', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://greenlane.superliquor.co.nz', 'https://greenlane.superliquor.co.nz/search?q='),
			('Super Liquor Helensville', 'Super Liquor', 'North Island', 'Auckland', 'Helensville', 'https://helensville.superliquor.co.nz', 'https://helensville.superliquor.co.nz/search?q='),
			('Super Liquor Highland Park', 'Super Liquor', 'North Island', 'Auckland', 'Manukau', 'https://highlandpark.superliquor.co.nz', 'https://highlandpark.superliquor.co.nz/search?q='),
			('Super Liquor Howick', 'Super Liquor', 'North Island', 'Auckland', 'Manukau', 'https://howick.superliquor.co.nz', 'https://howick.superliquor.co.nz/search?q='),
			('Super Liquor Huapai', 'Super Liquor', 'North Island', 'Auckland', 'Huapai', 'https://huapai.superliquor.co.nz', 'https://huapai.superliquor.co.nz/search?q='),
			('Super Liquor Mt Roskill', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://mtroskill.superliquor.co.nz', 'https://mtroskill.superliquor.co.nz/search?q='),
			('Super Liquor Orewa', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://hilltop.superliquor.co.nz', 'https://hilltop.superliquor.co.nz/search?q='),
			('Super Liquor Grand Drive', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://granddrive.superliquor.co.nz', 'https://granddrive.superliquor.co.nz/search?q='),
			('Super Liquor Pacific Square', 'Super Liquor', 'North Island', 'Auckland', 'Manukau', 'https://pacificsquare.superliquor.co.nz', 'https://pacificsquare.superliquor.co.nz/search?q='),
			('Super Liquor Poenamo', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://poenamo.superliquor.co.nz', 'https://poenamo.superliquor.co.nz/search?q='),
			('Super Liquor Pukekohe', 'Super Liquor', 'North Island', 'Auckland', 'Pukekohe', 'https://pukekohe.superliquor.co.nz', 'https://pukekohe.superliquor.co.nz/search?q='),
			('Super Liquor Red Beach', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://redbeach.superliquor.co.nz', 'https://redbeach.superliquor.co.nz/search?q='),
			('Super Liquor Snells Beach', 'Super Liquor', 'North Island', 'Auckland', 'Snells Beach', 'https://snellsbeach.superliquor.co.nz', 'https://snellsbeach.superliquor.co.nz/search?q='),
			('Super Liquor Whangaparaoa', 'Super Liquor', 'North Island', 'Auckland', 'Auckland', 'https://whangaparaoa.superliquor.co.nz', 'https://whangaparaoa.superliquor.co.nz/search?q='),
			('SuperValue Palomino', 'SuperValue', 'North Island', 'Auckland', 'Auckland', 'https://palomino.store.supervalue.co.nz', 'https://palomino.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Titirangi', 'SuperValue', 'North Island', 'Auckland', 'Auckland', 'https://titirangi.store.supervalue.co.nz', 'https://titirangi.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			/*Waikato*/
			('FreshChoice Leamington', 'FreshChoice', 'North Island', 'Waikato', 'Cambridge', 'https://leamington.store.freshchoice.co.nz', 'https://leamington.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Te Awamutu', 'FreshChoice', 'North Island', 'Waikato', 'Te Awamutu', 'https://teawamutu.store.freshchoice.co.nz', 'https://teawamutu.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('Big Barrel Te Awamutu', 'Big Barrel', 'North Island', 'Waikato', 'Te Awamutu', 'https://teawamutu.bigbarrel.co.nz', 'https://teawamutu.bigbarrel.co.nz/en/search?q='),
			('Super Liquor Frankton', 'Super Liquor', 'North Island', 'Waikato', 'Hamilton', 'https://frankton.superliquor.co.nz', 'https://frankton.superliquor.co.nz/search?q='),
			('Super Liquor Heaphy Terrace', 'Super Liquor', 'North Island', 'Waikato', 'Hamilton', 'https://heaphyterrace.superliquor.co.nz', 'https://heaphyterrace.superliquor.co.nz/search?q='),
			('Super Liquor Hillcrest', 'Super Liquor', 'North Island', 'Waikato', 'Hamilton', 'https://hillcrest.superliquor.co.nz', 'https://hillcrest.superliquor.co.nz/search?q='),
			('Super Liquor Huntly', 'Super Liquor', 'North Island', 'Waikato', 'Huntly', 'https://huntly.superliquor.co.nz', 'https://huntly.superliquor.co.nz/search?q='),
			('Super Liquor Matamata', 'Super Liquor', 'North Island', 'Waikato', 'Matamata', 'https://matamata.superliquor.co.nz', 'https://matamata.superliquor.co.nz/search?q='),
			('Super Liquor Morrinsville', 'Super Liquor', 'North Island', 'Waikato', 'Morrinsville', 'https://morrinsville.superliquor.co.nz', 'https://morrinsville.superliquor.co.nz/search?q='),
			('Super Liquor Putaruru', 'Super Liquor', 'North Island', 'Waikato', 'Putaruru', 'https://putaruru.superliquor.co.nz', 'https://putaruru.superliquor.co.nz/search?q='),
			('Super Liquor Sealey Street', 'Super Liquor', 'North Island', 'Waikato', 'Thames', 'https://sealeystreet.superliquor.co.nz', 'https://sealeystreet.superliquor.co.nz/search?q='),
			('Super Liquor Tairua', 'Super Liquor', 'North Island', 'Waikato', 'Tairua', 'https://tairua.superliquor.co.nz', 'https://tairua.superliquor.co.nz/search?q='),
			('Super Liquor Tauhara', 'Super Liquor', 'North Island', 'Waikato', 'Taupo', 'https://tauhara.superliquor.co.nz', 'https://tauhara.superliquor.co.nz/search?q='),
			('Super Liquor Te Awamutu', 'Super Liquor', 'North Island', 'Waikato', 'Te Awamutu', 'https://teawamutu.superliquor.co.nz', 'https://teawamutu.superliquor.co.nz/search?q='),
			('Super Liquor Tokoroa', 'Super Liquor', 'North Island', 'Waikato', 'Tokoroa', 'https://tokoroa.superliquor.co.nz', 'https://tokoroa.superliquor.co.nz/search?q='),
			('Super Liquor Thames', 'Super Liquor', 'North Island', 'Waikato', 'Thames', 'https://thames.superliquor.co.nz', 'https://thames.superliquor.co.nz/search?q='),
			('Super Liquor Waihi', 'Super Liquor', 'North Island', 'Waikato', 'Waihi', 'https://waihi.superliquor.co.nz', 'https://waihi.superliquor.co.nz/search?q='),
			('Super Liquor Whangamata', 'Super Liquor', 'North Island', 'Waikato', 'Whangamata', 'https://whangamata.superliquor.co.nz', 'https://whangamata.superliquor.co.nz/search?q='),
			('Super Liquor Whitianga', 'Super Liquor', 'North Island', 'Waikato', 'Whitianga', 'https://whitianga.superliquor.co.nz', 'https://whitianga.superliquor.co.nz/search?q='),
			('SuperValue Paetiki', 'SuperValue', 'North Island', 'Waikato', 'Taupo', 'https://paetiki.store.supervalue.co.nz', 'https://paetiki.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Parkwood', 'SuperValue', 'North Island', 'Waikato', 'Hamilton', 'https://parkwood.store.supervalue.co.nz', 'https://parkwood.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Pauanui', 'SuperValue', 'North Island', 'Waikato', 'Pauanui', 'https://pauanui.store.supervalue.co.nz', 'https://pauanui.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Raglan', 'SuperValue', 'North Island', 'Waikato', 'Raglan', 'https://raglan.store.supervalue.co.nz', 'https://raglan.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Waihi', 'SuperValue', 'North Island', 'Waikato', 'Waihi', 'https://waihi.store.supervalue.co.nz', 'https://waihi.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),			
			/*Bay of Plenty*/
			('FreshChoice Omokoroa', 'FreshChoice', 'North Island', 'Bay of Plenty', 'Tauranga', 'https://omokoroa.store.freshchoice.co.nz', 'https://omokoroa.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Papamoa', 'FreshChoice', 'North Island', 'Bay of Plenty', 'Tauranga', 'https://papamoa.store.freshchoice.co.nz', 'https://papamoa.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Rotorua', 'FreshChoice', 'North Island', 'Bay of Plenty', 'Rotorua', 'https://tengae.store.freshchoice.co.nz', 'https://tengae.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('Super Liquor Colonial', 'Super Liquor', 'North Island', 'Bay of Plenty', 'Rotorua', 'https://colonial.superliquor.co.nz', 'https://colonial.superliquor.co.nz/search?q='),
			('Super Liquor Greerton', 'Super Liquor', 'North Island', 'Bay of Plenty', 'Tauranga', 'https://greerton.superliquor.co.nz', 'https://greerton.superliquor.co.nz/search?q='),
			('Super Liquor Katikati', 'Super Liquor', 'North Island', 'Bay of Plenty', 'Katikati', 'https://katikati.superliquor.co.nz', 'https://katikati.superliquor.co.nz/search?q='),
			('Super Liquor Mitchell Downs', 'Super Liquor', 'North Island', 'Bay of Plenty', 'Rotorua', 'https://mitchelldowns.superliquor.co.nz', 'https://mitchelldowns.superliquor.co.nz/search?q='),
			('Super Liquor Mt Maunganui', 'Super Liquor', 'North Island', 'Bay of Plenty', 'Tauranga', 'https://mtmaunganui.superliquor.co.nz', 'https://mtmaunganui.superliquor.co.nz/search?q='),
			('Super Liquor Papamoa', 'Super Liquor', 'North Island', 'Bay of Plenty', 'Tauranga', 'https://papamoa.superliquor.co.nz', 'https://papamoa.superliquor.co.nz/search?q='),
			('Super Liquor Rotorua Central', 'Super Liquor', 'North Island', 'Bay of Plenty', 'Rotorua', 'https://rotoruacentral.superliquor.co.nz', 'https://rotoruacentral.superliquor.co.nz/search?q='),
			('Super Liquor Te Puke', 'Super Liquor', 'North Island', 'Bay of Plenty', 'Te Puke', 'https://tepuke.superliquor.co.nz', 'https://tepuke.superliquor.co.nz/search?q='),
			('Super Liquor Whakatane', 'Super Liquor', 'North Island', 'Bay of Plenty', 'Whakatane', 'https://whakatane.superliquor.co.nz', 'https://whakatane.superliquor.co.nz/search?q='),
			('SuperValue Pyes Pa', 'SuperValue', 'North Island', 'Bay of Plenty', 'Tauranga', 'https://pyespa.store.supervalue.co.nz', 'https://pyespa.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			/*Gisborne*/
			/*Hawkes Bay*/ 
			('Big Barrel Tamatea', 'Big Barrel', 'North Island', 'Hawkes Bay', 'Napier', 'https://tamatea.bigbarrel.co.nz', 'https://tamatea.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Marewa', 'Big Barrel', 'North Island', 'Hawkes Bay', 'Napier', 'https://marewa.bigbarrel.co.nz', 'https://marewa.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Carlyle', 'Big Barrel', 'North Island', 'Hawkes Bay', 'Napier', 'https://carlyle.bigbarrel.co.nz', 'https://carlyle.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Taradale', 'Big Barrel', 'North Island', 'Hawkes Bay', 'Napier', 'https://taradale.bigbarrel.co.nz', 'https://taradale.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Clive', 'Big Barrel', 'North Island', 'Hawkes Bay', 'Hastings', 'https://clive.bigbarrel.co.nz', 'https://clive.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Karamu', 'Big Barrel', 'North Island', 'Hawkes Bay', 'Hastings', 'https://karamu.bigbarrel.co.nz', 'https://karamu.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Havelock', 'Big Barrel', 'North Island', 'Hawkes Bay', 'Hastings', 'https://havelock.bigbarrel.co.nz', 'https://havelock.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Stortford', 'Big Barrel', 'North Island', 'Hawkes Bay', 'Hastings', 'https://stortford.bigbarrel.co.nz', 'https://stortford.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Waipukurau', 'Big Barrel', 'North Island', 'Hawkes Bay', 'Waipukurau', 'https://waipukurau.bigbarrel.co.nz', 'https://waipukurau.bigbarrel.co.nz/en/search?q='),
			('Super Liquor Waipawa', 'Super Liquor', 'North Island', 'Hawkes Bay', 'Waipawa', 'https://waipawa.superliquor.co.nz', 'https://waipawa.superliquor.co.nz/search?q='),			
			/*Taranaki*/
			('Big Barrel New Plymouth', 'Big Barrel', 'North Island', 'Taranaki', 'New Plymouth', 'https://newplymouth.bigbarrel.co.nz', 'https://newplymouth.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Devon Road', 'Big Barrel', 'North Island', 'Taranaki', 'New Plymouth', 'https://devonrd.bigbarrel.co.nz', 'https://devonrd.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Inglewood', 'Big Barrel', 'North Island', 'Taranaki', 'Inglewood', 'https://inglewood.bigbarrel.co.nz', 'https://inglewood.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Stratford', 'Big Barrel', 'North Island', 'Taranaki', 'Stratford', 'https://stratford.bigbarrel.co.nz', 'https://stratford.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Hawera', 'Big Barrel', 'North Island', 'Taranaki', 'Hawera', 'https://hawera.bigbarrel.co.nz', 'https://hawera.bigbarrel.co.nz/en/search?q='),
			('Super Liquor New Plymouth', 'Super Liquor', 'North Island', 'Taranaki', 'New Plymouth', 'https://newplymouth.superliquor.co.nz', 'https://newplymouth.superliquor.co.nz/search?q='),
			('Super Liquor Waitara', 'Super Liquor', 'North Island', 'Taranaki', 'Waitara', 'https://waitara.superliquor.co.nz', 'https://waitara.superliquor.co.nz/search?q='),
			('SuperValue Bell Block', 'SuperValue', 'North Island', 'Taranaki', 'Bell Block', 'https://bellblock.store.supervalue.co.nz', 'https://bellblock.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			/*Manawatu-Wanganui*/
			('Big Barrel Dannevirke', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Dannevirke', 'https://dannevirke.bigbarrel.co.nz', 'https://dannevirke.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Tremaine', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Palmerston North', 'https://tremaine.bigbarrel.co.nz', 'https://tremaine.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Princess', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Palmerston North', 'https://princess.bigbarrel.co.nz', 'https://princess.bigbarrel.co.nz/en/search?q='),			
			('Big Barrel Albert', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Palmerston North', 'https://albert.bigbarrel.co.nz', 'https://albert.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Cloverlea', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Palmerston North', 'https://cloverlea.bigbarrel.co.nz', 'https://cloverlea.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Highbury', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Palmerston North', 'https://highbury.bigbarrel.co.nz', 'https://highbury.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Feilding', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Feilding', 'https://feilding.bigbarrel.co.nz', 'https://feilding.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Kimbolton', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Feilding', 'https://kimbolton.bigbarrel.co.nz', 'https://kimbolton.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Whanganui', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Whanganui', 'https://whanganui.bigbarrel.co.nz', 'https://whanganui.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Victoria Ave', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Whanganui', 'https://victoria.bigbarrel.co.nz', 'https://victoria.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Riverside', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Whanganui', 'https://riverside.bigbarrel.co.nz', 'https://riverside.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Whanganui East', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Whanganui', 'https://whanganuieast.bigbarrel.co.nz', 'https://whanganuieast.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Pahiatua', 'Big Barrel', 'North Island', 'Manawatu-Wanganui', 'Pahiatua', 'https://pahiatua.bigbarrel.co.nz', 'https://pahiatua.bigbarrel.co.nz/en/search?q='),
			('Super Liquor Palmerston North', 'Super Liquor', 'North Island', 'Manawatu-Wanganui', 'Palmerston North', 'https://palmerstonnorth.superliquor.co.nz', 'https://palmerstonnorth.superliquor.co.nz/search?q='),
			('Super Liquor Taumarunui', 'Super Liquor', 'North Island', 'Manawatu-Wanganui', 'Taumarunui', 'https://taumarunui.superliquor.co.nz', 'https://taumarunui.superliquor.co.nz/search?q='),			
			('Super Liquor Woodville', 'Super Liquor', 'North Island', 'Manawatu-Wanganui', 'Woodville', 'https://woodville.superliquor.co.nz', 'https://woodville.superliquor.co.nz/search?q='),
			('SuperValue Wanganui', 'SuperValue', 'North Island', 'Manawatu-Wanganui', 'Whanganui', 'https://wanganui.store.supervalue.co.nz', 'https://wanganui.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),			
			/*Wellington*/
			('Big Barrel Masterton', 'Big Barrel', 'North Island', 'Wellington', 'Masterton', 'https://masterton.bigbarrel.co.nz', 'https://masterton.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Otaki', 'Big Barrel', 'North Island', 'Wellington', 'Otaki', 'https://otaki.bigbarrel.co.nz', 'https://otaki.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Lower Hutt', 'Big Barrel', 'North Island', 'Wellington', 'Lower Hutt', 'https://lowerhutt.bigbarrel.co.nz', 'https://lowerhutt.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Taita', 'Big Barrel', 'North Island', 'Wellington', 'Lower Hutt', 'https://centralhutt.bigbarrel.co.nz', 'https://centralhutt.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Waitangirua', 'Big Barrel', 'North Island', 'Wellington', 'Porirua', 'https://waitangirua.bigbarrel.co.nz', 'https://waitangirua.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Titahi Bay', 'Big Barrel', 'North Island', 'Wellington', 'Porirua', 'https://titahibay.bigbarrel.co.nz', 'https://titahibay.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Miramar', 'Big Barrel', 'North Island', 'Wellington', 'Wellington City', 'https://miramar.bigbarrel.co.nz', 'https://miramar.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Newtown', 'Big Barrel', 'North Island', 'Wellington', 'Wellington City', 'https://newtown.bigbarrel.co.nz', 'https://newtown.bigbarrel.co.nz/en/search?q='),
			('Super Liquor Johnsonville', 'Super Liquor', 'North Island', 'Wellington', 'Wellington City', 'https://johnsonville.superliquor.co.nz', 'https://johnsonville.superliquor.co.nz/search?q='),
			('Super Liquor Masterton', 'Super Liquor', 'North Island', 'Wellington', 'Masterton', 'https://masterton.superliquor.co.nz', 'https://masterton.superliquor.co.nz/search?q='),
			('Super Liquor Otaki', 'Super Liquor', 'North Island', 'Wellington', 'Otaki', 'https://otaki.superliquor.co.nz', 'https://otaki.superliquor.co.nz/search?q='),
			('SuperValue Cannons Creek', 'SuperValue', 'North Island', 'Wellington', 'Porirua', 'https://cannonscreek.store.supervalue.co.nz', 'https://cannonscreek.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Featherston', 'SuperValue', 'North Island', 'Wellington', 'Featherston', 'https://featherston.store.supervalue.co.nz', 'https://featherston.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Woburn', 'SuperValue', 'North Island', 'Wellington', 'Lower Hutt', 'https://woburn.store.supervalue.co.nz', 'https://woburn.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),			
/*South Island*/
			/*Marlborough*/
			('FreshChoice Picton', 'FreshChoice', 'South Island', 'Marlborough', 'Picton', 'https://picton.store.freshchoice.co.nz', 'https://picton.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),			
			('Super Liquor Grove Road', 'Super Liquor', 'South Island', 'Marlborough', 'Blenheim', 'https://groveroad.superliquor.co.nz', 'https://groveroad.superliquor.co.nz/search?q='),
			('SuperValue Renwick', 'SuperValue', 'South Island', 'Marlborough', 'Renwick', 'https://renwick.store.supervalue.co.nz', 'https://renwick.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),			
			/*Tasman*/
			('FreshChoice Richmond', 'FreshChoice', 'South Island', 'Tasman', 'Richmond', 'https://richmond.store.freshchoice.co.nz', 'https://richmond.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),			
			('FreshChoice Takaka', 'FreshChoice', 'South Island', 'Tasman', 'Takaka', 'https://takaka.store.freshchoice.co.nz', 'https://takaka.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('Big Barrel Richmond', 'Big Barrel', 'South Island', 'Tasman', 'Richmond', 'https://richmond.bigbarrel.co.nz', 'https://richmond.bigbarrel.co.nz/en/search?q='),
			('Super Liquor Golden Bay', 'Super Liquor', 'South Island', 'Tasman', 'Takaka', 'https://goldenbay.superliquor.co.nz', 'https://goldenbay.superliquor.co.nz/search?q='),
			('Super Liquor Motueka', 'Super Liquor', 'South Island', 'Tasman', 'Motueka', 'https://motueka.superliquor.co.nz', 'https://motueka.superliquor.co.nz/search?q='),
			('Super Liquor Richmond', 'Super Liquor', 'South Island', 'Tasman', 'Richmond', 'https://richmond.superliquor.co.nz', 'https://richmond.superliquor.co.nz/search?q='),
			/*Nelson*/
			('FreshChoice Nelson City', 'FreshChoice', 'South Island', 'Nelson', 'Nelson', 'https://nelsoncity.store.freshchoice.co.nz', 'https://nelsoncity.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),			
			('Big Barrel Nelson', 'Big Barrel', 'South Island', 'Nelson', 'Nelson', 'https://nelson.bigbarrel.co.nz', 'https://nelson.bigbarrel.co.nz/en/search?q='),
			('Super Liquor Nelson', 'Super Liquor', 'South Island', 'Nelson', 'Nelson', 'https://nelson.superliquor.co.nz', 'https://nelson.superliquor.co.nz/search?q='),
			('Super Liquor Tahunanui', 'Super Liquor', 'South Island', 'Nelson', 'Nelson', 'https://tahunanui.superliquor.co.nz', 'https://tahunanui.superliquor.co.nz/search?q='),
			('Super Liquor Tahunanui South', 'Super Liquor', 'South Island', 'Nelson', 'Nelson', 'https://tahunanuisouth.superliquor.co.nz', 'https://tahunanuisouth.superliquor.co.nz/search?q='),			
			/*Canterbury*/
			('FreshChoice Barrington', 'FreshChoice', 'South Island', 'Canterbury', 'Christchurch', 'https://barrington.store.freshchoice.co.nz', 'https://barrington.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice City Market', 'FreshChoice', 'South Island', 'Canterbury', 'Christchurch', 'https://citymarket.store.freshchoice.co.nz', 'https://citymarket.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Edgeware', 'FreshChoice', 'South Island', 'Canterbury', 'Christchurch', 'https://edgeware.store.freshchoice.co.nz', 'https://edgeware.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Merivale', 'FreshChoice', 'South Island', 'Canterbury', 'Christchurch', 'https://merivale.store.freshchoice.co.nz', 'https://merivale.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Parklands', 'FreshChoice', 'South Island', 'Canterbury', 'Christchurch', 'https://parklands.store.freshchoice.co.nz', 'https://parklands.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Geraldine', 'FreshChoice', 'South Island', 'Canterbury', 'Geraldine', 'https://geraldine.store.freshchoice.co.nz', 'https://geraldine.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),			
			('FreshChoice Leeston', 'FreshChoice', 'South Island', 'Canterbury', 'Leeston', 'https://leeston.store.freshchoice.co.nz', 'https://leeston.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Oxford', 'FreshChoice', 'South Island', 'Canterbury', 'Oxford', 'https://oxford.store.freshchoice.co.nz', 'https://oxford.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Prebbleton', 'FreshChoice', 'South Island', 'Canterbury', 'Prebbleton', 'https://prebbleton.store.freshchoice.co.nz', 'https://prebbleton.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('Super Liquor Amberley', 'Super Liquor', 'South Island', 'Canterbury', 'Amberley', 'https://amberley.superliquor.co.nz', 'https://amberley.superliquor.co.nz/search?q='),
			('Super Liquor Barrington', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://barrington.superliquor.co.nz', 'https://barrington.superliquor.co.nz/search?q='),
			('Super Liquor Belfast', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://belfast.superliquor.co.nz', 'https://belfast.superliquor.co.nz/search?q='),
			('Super Liquor Brighton', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://brighton.superliquor.co.nz', 'https://brighton.superliquor.co.nz/search?q='),
			('Super Liquor Burnside', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://burnside.superliquor.co.nz', 'https://burnside.superliquor.co.nz/search?q='),
			('Super Liquor Colombo Street', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://colombostreet.superliquor.co.nz', 'https://colombostreet.superliquor.co.nz/search?q='),
			('Super Liquor Edgeware', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://edgeware.superliquor.co.nz', 'https://edgeware.superliquor.co.nz/search?q='),
			('Super Liquor Elmwood', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://elmwood.superliquor.co.nz', 'https://elmwood.superliquor.co.nz/search?q='),
			('Super Liquor Halswell', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://halswell.superliquor.co.nz', 'https://halswell.superliquor.co.nz/search?q='),
			('Super Liquor Hanmer Springs', 'Super Liquor', 'South Island', 'Canterbury', 'Hanmer Springs', 'https://hanmersprings.superliquor.co.nz', 'https://hanmersprings.superliquor.co.nz/search?q='),
			('Super Liquor Hornby', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://hornby.superliquor.co.nz', 'https://hornby.superliquor.co.nz/search?q='),
			('Super Liquor Ilam', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://ilam.superliquor.co.nz', 'https://ilam.superliquor.co.nz/search?q='),
			('Super Liquor Kaiapoi', 'Super Liquor', 'South Island', 'Canterbury', 'Kaiapoi', 'https://kaiapoi.superliquor.co.nz', 'https://kaiapoi.superliquor.co.nz/search?q='),
			('Super Liquor Leeston', 'Super Liquor', 'South Island', 'Canterbury', 'Leeston', 'https://leeston.superliquor.co.nz', 'https://leeston.superliquor.co.nz/search?q='),
			('Super Liquor Methven', 'Super Liquor', 'South Island', 'Canterbury', 'Methven', 'https://methven.superliquor.co.nz', 'https://methven.superliquor.co.nz/search?q='),
			('Super Liquor Papanui', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://papanui.superliquor.co.nz', 'https://papanui.superliquor.co.nz/search?q='),
			('Super Liquor Twizel', 'Super Liquor', 'South Island', 'Canterbury', 'Twizel', 'https://twizel.superliquor.co.nz', 'https://twizel.superliquor.co.nz/search?q='),
			('Super Liquor Woolston', 'Super Liquor', 'South Island', 'Canterbury', 'Christchurch', 'https://woolston.superliquor.co.nz', 'https://woolston.superliquor.co.nz/search?q='),
			('SuperValue Fendalton', 'SuperValue', 'South Island', 'Canterbury', 'Christchurch', 'https://fendalton.store.supervalue.co.nz', 'https://fendalton.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Lyttleton', 'SuperValue', 'South Island', 'Canterbury', 'Lyttleton', 'https://lyttelton.store.supervalue.co.nz', 'https://lyttelton.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Methven', 'SuperValue', 'South Island', 'Canterbury', 'Methven', 'https://methven.store.supervalue.co.nz', 'https://methven.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Sumner', 'SuperValue', 'South Island', 'Canterbury', 'Christchurch', 'https://sumner.store.supervalue.co.nz', 'https://sumner.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Tinwald', 'SuperValue', 'South Island', 'Canterbury', 'Ashburton', 'https://tinwald.store.supervalue.co.nz', 'https://tinwald.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			/*West Coast*/
			('FreshChoice Westport', 'FreshChoice', 'South Island', 'West Coast', 'Westport', 'https://westport.store.freshchoice.co.nz', 'https://westport.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('Super Liquor Greymouth', 'Super Liquor', 'South Island', 'West Coast', 'Greymouth', 'https://greymouth.superliquor.co.nz', 'https://greymouth.superliquor.co.nz/search?q='),
			('Super Liquor Hokitika', 'Super Liquor', 'South Island', 'West Coast', 'Hokitika', 'https://hokitika.superliquor.co.nz', 'https://hokitika.superliquor.co.nz/search?q='),
			('SuperValue Reefton', 'SuperValue', 'South Island', 'West Coast', 'Reefton', 'https://reefton.store.supervalue.co.nz', 'https://reefton.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),						
			/*Otago*/
			('FreshChoice Cromwell', 'FreshChoice', 'South Island', 'Otago', 'Cromwell', 'https://cromwell.store.freshchoice.co.nz', 'https://cromwell.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Green Island', 'FreshChoice', 'South Island', 'Otago', 'Dunedin', 'https://greenisland.store.freshchoice.co.nz', 'https://greenisland.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Roslyn', 'FreshChoice', 'South Island', 'Otago', 'Dunedin', 'https://roslyn.store.freshchoice.co.nz', 'https://roslyn.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),
			('FreshChoice Queenstown', 'FreshChoice', 'South Island', 'Otago', 'Queenstown', 'https://queenstown.store.freshchoice.co.nz', 'https://queenstown.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),			
			('Big Barrel Andersons Bay', 'Big Barrel', 'South Island', 'Otago', 'Dunedin', 'https://andersonsbay.bigbarrel.co.nz', 'https://andersonsbay.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Concord', 'Big Barrel', 'South Island', 'Otago', 'Dunedin', 'https://concord.bigbarrel.co.nz', 'https://concord.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Kaikorai Valley', 'Big Barrel', 'South Island', 'Otago', 'Dunedin', 'https://kaikorai.bigbarrel.co.nz', 'https://kaikorai.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Mosgiel', 'Big Barrel', 'South Island', 'Otago', 'Dunedin', 'https://mosgiel.bigbarrel.co.nz', 'https://mosgiel.bigbarrel.co.nz/en/search?q='),
			('Big Barrel Queenstown', 'Big Barrel', 'South Island', 'Otago', 'Queenstown', 'https://remarkables.bigbarrel.co.nz', 'https://remarkables.bigbarrel.co.nz/en/search?q='),
			('Super Liquor Alexandra', 'Super Liquor', 'South Island', 'Otago', 'Alexandra', 'https://alexandra.superliquor.co.nz', 'https://alexandra.superliquor.co.nz/search?q='),
			('Super Liquor Balclutha', 'Super Liquor', 'South Island', 'Otago', 'Balclutha', 'https://balclutha.superliquor.co.nz', 'https://balclutha.superliquor.co.nz/search?q='),
			('Super Liquor Cromwell', 'Super Liquor', 'South Island', 'Otago', 'Cromwell', 'https://cromwell.superliquor.co.nz', 'https://cromwell.superliquor.co.nz/search?q='),
			('Super Liquor Oamaru', 'Super Liquor', 'South Island', 'Otago', 'Oamaru', 'https://oamaru.superliquor.co.nz', 'https://oamaru.superliquor.co.nz/search?q='),
			('Super Liquor Remarkables Park', 'Super Liquor', 'South Island', 'Otago', 'Queenstown', 'https://remarkablespark.superliquor.co.nz', 'https://remarkablespark.superliquor.co.nz/search?q='),
			('Super Liquor Shotover Street', 'Super Liquor', 'South Island', 'Otago', 'Queenstown', 'https://shotoverst.superliquor.co.nz', 'https://shotoverst.superliquor.co.nz/search?q='),
			('Super Liquor Wanaka', 'Super Liquor', 'South Island', 'Otago', 'Wanaka', 'https://wanaka.superliquor.co.nz', 'https://wanaka.superliquor.co.nz/search?q='),
			('SuperValue Milton', 'SuperValue', 'South Island', 'Otago', 'Milton', 'https://milton.store.supervalue.co.nz', 'https://milton.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Roxburgh', 'SuperValue', 'South Island', 'Otago', 'Roxburgh', 'https://roxburgh.store.supervalue.co.nz', 'https://roxburgh.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),			
			/*Southland*/
			('FreshChoice Te Anau', 'FreshChoice', 'South Island', 'Southland', 'Te Anau', 'https://teanau.store.freshchoice.co.nz', 'https://teanau.store.freshchoice.co.nz/search?utf8=%E2%9C%93&q='),			
			('Super Liquor Invercargill', 'Super Liquor', 'South Island', 'Southland', 'Invercargill', 'https://collingwood.superliquor.co.nz', 'https://collingwood.superliquor.co.nz/search?q='),
			('Super Liquor Southland', 'Super Liquor', 'South Island', 'Southland', 'Invercargill', 'https://southland.superliquor.co.nz', 'https://southland.superliquor.co.nz/search?q='),
			('Super Liquor Lorneville', 'Super Liquor', 'South Island', 'Southland', 'Wallacetown', 'https://lorneville.superliquor.co.nz', 'https://lorneville.superliquor.co.nz/search?q='),
			('SuperValue Otautau', 'SuperValue', 'South Island', 'Southland', 'Otautau', 'https://otautau.store.supervalue.co.nz', 'https://otautau.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Plaza', 'SuperValue', 'South Island', 'Southland', 'Invercargill', 'https://plaza.store.supervalue.co.nz', 'https://plaza.store.supervalue.co.nz/search?utf8=%E2%9C%93&q='),
			('SuperValue Riverton', 'SuperValue', 'South Island', 'Southland', 'Riverton', 'https://riverton.store.supervalue.co.nz', 'https://riverton.store.supervalue.co.nz/search?utf8=%E2%9C%93&q=');
